/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as ApiPublicYocoWebhookRouteImport } from './routes/api/public/yoco-webhook'
import { Route as ApiPublicPreviewSplatRouteImport } from './routes/api/public/preview/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicYocoWebhookRoute = ApiPublicYocoWebhookRouteImport.update({
  id: '/api/public/yoco-webhook',
  path: '/api/public/yoco-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPreviewSplatRoute = ApiPublicPreviewSplatRouteImport.update({
  id: '/api/public/preview/$',
  path: '/api/public/preview/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/events/$slug': typeof EventsSlugRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/events/': typeof EventsIndexRoute
  '/api/public/yoco-webhook': typeof ApiPublicYocoWebhookRoute
  '/api/public/preview/$': typeof ApiPublicPreviewSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/events/$slug': typeof EventsSlugRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/events': typeof EventsIndexRoute
  '/api/public/yoco-webhook': typeof ApiPublicYocoWebhookRoute
  '/api/public/preview/$': typeof ApiPublicPreviewSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/events/$slug': typeof EventsSlugRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/events/': typeof EventsIndexRoute
  '/api/public/yoco-webhook': typeof ApiPublicYocoWebhookRoute
  '/api/public/preview/$': typeof ApiPublicPreviewSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/events/$slug'
    | '/orders/$orderId'
    | '/events/'
    | '/api/public/yoco-webhook'
    | '/api/public/preview/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/events/$slug'
    | '/orders/$orderId'
    | '/events'
    | '/api/public/yoco-webhook'
    | '/api/public/preview/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/events/$slug'
    | '/orders/$orderId'
    | '/events/'
    | '/api/public/yoco-webhook'
    | '/api/public/preview/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  EventsSlugRoute: typeof EventsSlugRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
  ApiPublicYocoWebhookRoute: typeof ApiPublicYocoWebhookRoute
  ApiPublicPreviewSplatRoute: typeof ApiPublicPreviewSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/yoco-webhook': {
      id: '/api/public/yoco-webhook'
      path: '/api/public/yoco-webhook'
      fullPath: '/api/public/yoco-webhook'
      preLoaderRoute: typeof ApiPublicYocoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/preview/$': {
      id: '/api/public/preview/$'
      path: '/api/public/preview/$'
      fullPath: '/api/public/preview/$'
      preLoaderRoute: typeof ApiPublicPreviewSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  EventsSlugRoute: EventsSlugRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  EventsIndexRoute: EventsIndexRoute,
  ApiPublicYocoWebhookRoute: ApiPublicYocoWebhookRoute,
  ApiPublicPreviewSplatRoute: ApiPublicPreviewSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
